### ISSUE TITLE
Next.jsの初期環境設定について

### ISSUE THREAD

**Issue by ganbon** [kmsz46/chatblog#1]
ローカルで`yarn create next-app --typescript`を行うとpullすることが難しいので

  1. `git pull origin front:front-名前`で最新の環境を持ってくる
  2. `cd front`で移動し`yarn install`or`npm install`でignoreで用意されていない設定ファイルを持ってくる

の手順で行うとスムーズに構築可能だと思います

構築例
```
git pull origin front-yoroshiku:front-ganbon
cd frontend
yarn install
yarn dev
```

**Comment by kmsz46** [comment]
コメントありがとうございます！
確かにpullしてきてから、各自インストールしてもらった方がいいですね！
書き換えておきます！

**Comment by ganbon** [comment]
closeしておきます
